-- Find total customers by country
SELECT 
	country,
    COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC;

-- Find total customers by gender
SELECT
	gender,
    COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC;

-- Find total product by category
SELECT
	category,
    COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC;

-- What is the average cost by category
SELECT 
	category,
    ROUND(AVG(cost), 2) AS average_costs
FROM gold.dim_products
GROUP BY category
ORDER BY average_costs DESC;

-- What is the total revenue generated for each category
SELECT 
	p.category,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_products AS p
	ON f.product_key = p.product_key
GROUP BY category
ORDER BY total_revenue DESC;

-- Find total revenue generated by each customers
SELECT 
	c.customer_number,
    c.first_name,
    c.last_name,
	SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_customers AS c
	ON f.customer_key = c.customer_key
GROUP BY c.customer_number, c.first_name, c.last_name
ORDER BY total_revenue DESC;

-- What is the distribution of sold items across the countries
SELECT
	c.country,
    SUM(quantity) AS total_quantity
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_customers AS c
	ON f.customer_key = c.customer_key
GROUP BY c.country
ORDER BY total_quantity DESC
